M48
; DRILL file {KiCad (6.0.5)} date Tue 21 Jun 2022 13:53:15 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-21T13:53:15+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0709
%
G90
G05
T1
X2.5976Y-2.3862
X2.5976Y-2.6138
T2
X2.2Y-3.0
X2.3Y-3.0
X2.4Y-3.0
T3
X1.7Y-1.9
X1.7Y-2.1
X2.2Y-2.0
T0
M30
